from sqlalchemy.orm import Session
from . import models, schemas, security

# ==========================================
# USER OPERATIONS
# ==========================================

def get_user_by_email(db: Session, email: str):
    """READ: Find a user by their email (useful for login/signup validation)."""
    return db.query(models.User).filter(models.User.email == email).first()

def get_user_by_username(db: Session, username: str):
    """READ: Find a user by their username"""
    return db.query(models.User).filter(models.User.username == username).first()

def create_user(db: Session, user: schemas.UserCreate):
    """CREATE: Securely hash the password and save the new user."""
    # 1. Security: Hash the password IMMEDIATELY
    hashed_pwd = security.get_password_hash(user.password)

    # 2. Database: Create the SQLAlchemy model instance
    db_user = models.User(
        username=user.username,
        email=user.email,
        hashed_password=hashed_pwd
    )
    
    # 3. Database: Save to the database
    db.add(db_user)
    db.commit()
    db.refresh(db_user) # Updates the object with the new ID generated by the database
    
    return db_user

# ==========================================
# JOURNAL ENTRY OPERATIONS
# ==========================================

def create_user_entry(db: Session, entry: schemas.EntryCreate, user_id: int):
    """CREATE: Save a new journal entry linked to a specific user."""
    # Note: We will add the 'encryption at rest' logic here later!
    # model_dump() converts the Pydantic schema into a standard Python dictionary
    db_entry = models.Entry(**entry.model_dump(), owner_id=user_id)
    
    db.add(db_entry)
    db.commit()
    db.refresh(db_entry)
    
    return db_entry

def get_user_entries(db: Session, user_id: int, skip: int = 0, limit: int = 100):
    """READ: Fetch entries for a specific user, with pagination (skip/limit)."""
    return db.query(models.Entry).filter(models.Entry.owner_id == user_id).offset(skip).limit(limit).all()